activewiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('events/', include('events.urls')),
    path('facts/', include('facts.urls')),
    path('resources/', include('resources.urls')),
    path('users/', include('users.urls')),
    path('outreach/', include('arvo.urls')),
    path('badmin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

arvo/urls.py
from django.urls import path

from . import views

app_name = 'arvo'
urlpatterns = [
    path('', views.index, name='index'),
    path('facts/', views.facts, name='facts'),
    path('facts/<str:tag_name>/', views.facts, name='facts'),
    path('responses/', views.responses, name='responses'),
    path('resources/', views.resources, name='resources'),
    path('codeofconduct/', views.code_of_conduct, name='code_of_conduct'),
    path('about/', views.about, name='about')
]

facts/urls.py
from django.urls import path

from . import views

app_name = 'facts'
urlpatterns = [
    path('', views.index, name='index'),
    path('submit/', views.submit, name='submit'),
    path('<int:fact_id>/', views.detail, name='detail'),
    path('<str:paths>/', views.index, name='index_tags'),
]

arvo/models.py
from django.db import models

from main.models import Tag
from facts.models import Fact

class ArvoFactReference(models.Model):
    name = models.CharField(max_length=200, blank=True)
    parent = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, related_name='children')
    fact = models.ForeignKey(Fact, on_delete=models.PROTECT, null=True, blank=True, related_name='arvo_references')
    # order = models.IntegerField()
    
    def __str__(self):
        r = self.name
        p = self.parent
        while p:
            r = p.name + ' - ' + r
            p = p.parent
        return r
    
    
    class Meta:
        ordering = ['name']



class ArvoResponse(models.Model):
    name = models.CharField(max_length=1000)
    description = models.TextField(blank=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name='arvo_responses')
    
    def __str__(self):
        return self.name

facts/models.py
from django.db import models
from main.models import Tag, SubmissionStatus, Cause
from users.models import User


class FactSource(models.Model):
    title = models.CharField(max_length=200)
    publication = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    
    def __str__(self):
        return self.title
    
class FactTag(models.Model):
    display_name = models.CharField(max_length=200)
    path_name = models.CharField(max_length=200)
    parent_tag = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, related_name='child_tags')
    
    def __str__(self):
        return self.display_name

class Fact(models.Model):
    text = models.CharField(max_length=1000)
    number = models.IntegerField(unique=True)
    extra_text = models.TextField(blank=True)
    tags = models.ManyToManyField(FactTag, related_name='facts', blank=True)
    causes = models.ManyToManyField(Cause, related_name='facts')
    sources = models.ManyToManyField(FactSource, related_name='facts', blank=True)
    submitted_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='facts', null=True, blank=True)
    submission_status = models.ForeignKey(SubmissionStatus, on_delete=models.PROTECT, related_name='facts')
    created_timestamp = models.DateTimeField(auto_now_add=True)
    edited_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.sources.count() == 0:
            return '(NEEDS SOURCES) ' + self.text
        return self.text
    

arvo/views.py
from django.shortcuts import render

from .models import ArvoFactReference, ArvoResponse
from facts.models import Fact
from main.models import Tag

def index(request):
    return render(request, 'arvo/index.html', {})

def code_of_conduct(request):
    return render(request, 'arvo/code_of_conduct.html', {})


def facts(request, tag_name=''):
    fact_reference = ArvoFactReference.objects.filter(name=tag_name).first()
    child_references = None
    facts = None
    if fact_reference:
        child_references = fact_reference.children.filter(fact__isnull=True)
        facts = [fr.fact for fr in fact_reference.children.filter(fact__isnull=False)]
    else:
        child_references = ArvoFactReference.objects.filter(fact__isnull=True, parent__isnull=True)
        facts = []
    
    context = {
        'tag_name': tag_name,
        'child_references': child_references,
        'facts': facts
    }
    return render(request, 'arvo/facts.html', context)
    
    

def responses(request):
    context = {
        'responses': ArvoResponse.objects.order_by('name')
    }
    return render(request, 'arvo/responses.html', context)
    
def about(request):
    return render(request, 'arvo/about.html', {})


def resources(request):
    return render(request, 'arvo/resources.html', {})

facts/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404

from facts.models import Fact, FactTag, FactSource
from main.models import SubmissionStatus, Subdomain, Cause

from main import parameter_parser

# TODO: sort by popularity when users can 'like' a fact
# show the number of likes


def submit(request):
    if request.method == 'POST':
        pass
    return render(request, 'facts/submit.html')

def detail(request, fact_id):
    context = {
        'fact': Fact.objects.get(pk=fact_id)
    }
    return render(request, 'facts/detail.html', context)

def index(request, paths=''):
    params = parameter_parser.parse_parameters(request.META, request.GET, paths, FactTag)
    subdomain = params['subdomain']
    page = params['page']
    selected_cause = params['cause']
    selected_tag = params['tag']


    approved_status = SubmissionStatus.objects.get(name='approved')
    facts = Fact.objects.filter(submission_status_id=approved_status.id)


    # filter by cause
    if selected_cause is not None:
        facts = facts.filter(causes__in=[selected_cause.id])

    # filter by tag
    if selected_tag is not None:
        facts = facts.filter(tags__in=[selected_tag.id])




    facts_per_page = 20
    paginator = Paginator(facts, facts_per_page)
    try:
        facts = paginator.page(page)
    except (EmptyPage, PageNotAnInteger):
        raise Http404

    causes = Cause.objects.order_by('name')
    tags = FactTag.objects.order_by('display_name')


    context = {
        'data_type': 'facts',
        'data_type_singular': 'fact',
        'subdomain': subdomain,
        'subdomains': Subdomain.objects.order_by('name'),
        'objects': facts,
        'tags': tags,
        'causes': causes,
        'selected_tag': selected_tag,
        'selected_cause': selected_cause,
    }

    return render(request, 'main/data_list.html', context)

arvo/templates/arvo/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} - Outreach - About{% endblock %}
{% block main %}
<style type="text/css">

  .main_container {

    padding:20px;
  }
  .mask_slide_title {
    position:absolute;
    top:0;
    text-align:center;
    width:100%;
    text-shadow: 0 0 6px black;
    font-size:32px;
  }
  .mask_slide_title a {
    color:white;
  }
  .carousel-fixed-item {
    display:flex;
    flex-direction:row;
    justify-content:space-between;
    top:45%;
    padding:0px 10px;
  }
</style>
<div class="main_container">
  <div class="page_title"><a href="{% url 'arvo:index' %}">Outreach</a> - About (work in progress)</div>
  <p>Outreach (ARVO) is a method of educating the public about animal agriculture, veganism, and animal rights. The basic idea is to show footage from slaughterhouses, dairy farms, and egg farms, fisheries, etc, in public areas. Outreachers can then approach people watching the footage and talk with them to give context and advocate that they go vegan. It can be performed effectively with both a small or large budget.</p>
  <p>Note: depending on the country, city, and location, there may be restrictions on showing graphic footage in public, wearing masks, playing music, or even demonstrating on public property. Please check the local laws before organizing an event.</p>
  <h2>Organizations</h2>
  <p>There are multiple organizations that organize video outreach events</p>
  <ul>
    <li><a href="https://www.anonymousforthevoiceless.org/">Anonymous for the Voiceless</a></li>
    <li><a href="https://theearthlingsexperience.com/">Earthlings Experience</a></li>
    <li><a href="https://www.facebook.com/justiceforanimalsoutreach/">Justice for Animals</a></li>
    <li><a href="https://www.rootsofmorality.org/">Roots of Morality</a></li>
    <li><a href="https://www.collectivelyfree.org/">Collectively Free</a></li>
    <li><a href="https://buildpeace.org/">PEACE</a></li>
    <li><a href="https://www.facebook.com/groups/VoicesoftheDamned/">Voices of the Damned</a></li>
  </ul>
  <div class="carousel carousel-slider center">
    <div class="carousel-fixed-item">
      <a class="btn waves-effect bt_prev"><</a>
      <a class="btn waves-effect bt_next">></a>
    </div>
    <div class="carousel-item" href="#one!">
      <img src="{% static '/arvo/masks/anonymous_for_the_voiceless.jpg' %}"/>
      <div class="mask_slide_title"><a href="https://www.anonymousforthevoiceless.org/">Anonymous for the Voiceless</a></div>
    </div>
    <div class="carousel-item" href="#two!">
      <img src="{% static '/arvo/masks/earthlings_experience.jpg' %}"/>
      <div class="mask_slide_title"><a href="https://theearthlingsexperience.com/">Earthlings Experience</a></div>
    </div>
    <div class="carousel-item" href="#three!">
      <img src="{% static '/arvo/masks/peace.jpg' %}"/>
      <div class="mask_slide_title"><a href="https://buildpeace.org/">PEACE</a></div>
    </div>
    <div class="carousel-item" href="#four!">
      <img src="{% static '/arvo/masks/justice_for_animals.jpg' %}"/>
      <div class="mask_slide_title"><a href="https://www.facebook.com/justiceforanimalsoutreach/">Justice for Animals</a></div>
    </div>
    <div class="carousel-item" href="#five!">
      <img src="{% static '/arvo/masks/roots_of_morality.jpg' %}"/>
      <div class="mask_slide_title"><a href="https://www.rootsofmorality.org/">Roots of Morality</a></div>
    </div>
    <div class="carousel-item" href="#six!">
      <img src="{% static '/arvo/masks/collectively_free.jpg' %}"/>
      <div class="mask_slide_title"><a href="https://www.collectivelyfree.org/">Collectively Free</a></div>
    </div>
  </div>
  <h2>Videos</h2>
  <p>There are many sources of videos, from documentaries to undercover investigations. Most usage should fall under fair use.</p>
  <ul>
    <li><a href="https://www.youtube.com/playlist?list=PLvfUGUfFj_6wFmc3wZTtRVdKTDKsXMyse">Mercy for Animals - Undercover Investigations</a></li>
    <li><a href="https://www.dominionmovement.com/">Dominion</a></li>
    <li><a href="https://www.nationearth.com/">Earthlings</a></li>
    <li><a href="https://www.landofhopeandglory.org/">Land of Hope and Glory</a></li>
    <li><a href="https://www.aussiepigs.com/lucent">Lucent</a></li>
  </ul>
  <h2>Masks</h2>
  <p>Covering your face helps onlookers focus on the footage without the sense someone is staring at them, it can also add to the aesthetic of the installation.</p>
  <ul>
    <li><a href="https://en.wikipedia.org/wiki/Guy_Fawkes_mask">Guy Fawkes Masks</a></li>
    <li>Plain White Masks</li>
    <li>Black Tape Over Mouth</li>
    <li>Sunglasses</li>
    <li>Blindfolds</li>
    <li>Dust/Surgical Masks</li>
  </ul>
  <h2>Music</h2>
  <p>Music may be played through a speaker to create atmosphere and grab people's attention.</p>
  <ul>
  <li><a href="https://open.spotify.com/playlist/17rjh6RuqPkkMgclDQ9I6I">Justice for Animals</a></li>
  <li><a herf="https://open.spotify.com/playlist/189qb58hZa3PDsyvBCb0y8">Anonymous for the Voiceless</a></li>
  </ul>
  <h2>Leaflets, Pamphlets, & Booklets</h2>
  <p>Literature may be distributed to give people something they can take home.</p>
  <ul>
    <li><a href="https://www.petaliterature.com/">Peta</a></li>
    <li><a href="https://veganoutreach.org/order-form/">Vegan Outreach</a></li>
    <li><a href="https://www.viva.org.uk/resources/campaign-materials/leaflets">Viva!</a></li>
    <li><a href="https://www.animalaid.org.uk/the-issues/campaigns-resources/leaflets/">Animal Aid</a></li>
    <li><a href="https://www.vegansociety.com/resources/publications-and-video/leaflets">The Vegan Society</a></li>
    <li><a href="http://www.howdoigovegan.com/abolitionist-veganism/outreach-materials/">HowDoIGoVegan.com</a></li>
    <li><a href="https://www.nhes.org/product-category/brochures/">National Humane Education Society</a></li>
  </ul>
  <h2>Resource Cards</h2>
  <p>People are often more open to taking a card than an entire pamphlet, many examples are listed below.</p>
  <ul>
    <li><a class="carousel-item" href="{% static 'arvo/outreach_cards/anonymous_for_the_voiceless.jpg' %}">Anonymous for the Voiceless</a></li>
    <li><a class="carousel-item" href="{% static 'arvo/outreach_cards/cheyenne.jpg' %}">Naturally Cheyenne</a></li>
    <li><a class="carousel-item" href="{% static 'arvo/outreach_cards/animal_rights_toronto.jpg' %}">Animal Rights Toronto</a></li>
    <li><a class="carousel-item" href="{% static 'arvo/outreach_cards/justice_for_animals.jpg' %}">Justice for Animals</a></li>
    <li><a class="carousel-item" href="{% static 'arvo/outreach_cards/the_save_movement.jpg' %}">The Save Movement</a></li>
    <li><a class="carousel-item" href="{% static 'arvo/outreach_cards/we_care_about_animals.jpg' %}">We Care About Animals</a></li>
    <li><a class="carousel-item" href="{% static 'arvo/outreach_cards/vigorous_vegan_vagabond.jpg' %}">The Vigorous Vegan Vagabond</a></li>
    <li><a class="carousel-item" href="{% static 'arvo/outreach_cards/voices_of_the_damned.jpg' %}">Voices of the Damned</a></li>
  </ul>

  <h2>Promotion</h2>
  <ul>
    <li>Make posts in facebook groups</li>
    <li>Post flyers in coffee shops, or around campus</li>
    <li>On facebook, you can create <a href="https://www.facebook.com/help/572885262883136/">events</a>, <a href="https://www.facebook.com/help/104002523024878">pages</a> to host them, and <a href="https://www.facebook.com/help/167970719931213">group to plan</a></li>
  </ul>
  <h2>Outreach</h2>
  <p>By standing beside the person and watching the footage along with them, you're joining them in acknowledging the reality that the video conveys. If the organizer wants to keep track of how effective their actions are, outreachers can keep a tally of conversations they felt left an impact.</p>

  <a href="https://www.amazingveganoutreach.com/learnonline">Amazing Vegan Outreach</a>
</div>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, {});
  });

  let carousel_elements = document.querySelectorAll('.carousel')
  let carousel_instances = M.Carousel.init(carousel_elements, {
    fullWidth: true,
    indicators: true
  });
  for (let i=0; i<carousel_elements.length; ++i) {
    let bt_prev = carousel_elements[i].querySelector('.bt_prev')
    let bt_next = carousel_elements[i].querySelector('.bt_next')
    bt_prev.onclick = function() {
      carousel_instances[i].prev()
    }
    bt_next.onclick = function() {
      carousel_instances[i].next()
    }
  }
</script>
{% endblock %}

arvo/templates/arvo/code_of_conduct.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} - Outreach - Code of Conduct{% endblock %}
{% block main %}
<style type="text/css">
  .page_content {
    font-size:20px;
  }
  .page_title {
    margin-bottom:0;
  }
</style>
<div class="page_title">Code of Conduct</div>
<nav class="breadcrumbs">
  <div class="nav-wrapper">
    <div class=" col s12">
      <a href="{% url 'arvo:index' %}" class="breadcrumb">Outreach</a>
      <a href="#!" class="breadcrumb">Code of Conduct</a>
    </div>
  </div>
</nav>
<div class="page_content">
  <p><b>Nonviolence in action, word, and tone</b>, for how we speak to the public, and how we speak to eachother. This means we do not tolerate bullying, harassment, threats, intimidation, condescension, manipulation, or hate-speech. We are respectful and inclusive of people of all ages, abilities, genders, cultures, ethnicities, and religious backgrounds.</p>
  <p><b>Respect for the non-vegans we outreach</b>. We meet people where they're at, and give them the knowledge and resources to connect their actions with their values. We can be direct without being aggressive and polite without being servile. The most effective form of outreach is a balance between the two. If people become aggressive, we disengage from conversation and alert an organizer.</p>
  <p><b>Objectivity in our facts and explanations</b>. We won't cite exaggerated statistics or over-emphasize rare or outdated practices. We should focus on standard industry practice in factory farming, which accounts for the overwhelming majority of animal products sold, and on the most recent scientific data available. By sticking to hard facts, we escape the more nebulous realm of opinion. The truth is on our side.</p>
  <p>By attending these events, you agree to uphold these values. By maintaining a safe, inclusive, and academic space, we can be most effective in raising the public's awareness about animal agriculture and animal rights, and impacting the industry by reducing demand for animal products.</p>
</div>
{% endblock %}

arvo/templates/arvo/facts.html
{% extends 'main/base.html' %}
{% block title %} - Outreach - Facts{% if tag_name %} about {{tag_name | title}}{% endif %}{% endblock %}
{% block main %}

<style type="text/css">

  .children .collapsible-header {
    margin-bottom:20px;
  }

  .children .collapsible-header a {
    text-align:center;
    width:100%;
    height:100%;
    display:block;
    font-size:24px;
  }

  .collapsible li {
    margin-top: 20px;
  }

  .fact_text {
    padding:10px;
    font-size:20px;
  }
  .fact_button_bar {
    padding:10px;
    display:flex;
    font-size:18px;
    flex-direction:row;
    justify-content:space-between;
  }

  .collapsible li.active i {
    -ms-transform: rotate(180deg); /* IE 9 */
    -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
    transform: rotate(180deg);
  }

  .collapsible hr {
    width:100%;
  }

  .fact_header {
    display:flex;
    flex-direction:row;
    justify-content:space-between;
    align-items:center;
  }


  .sources_title {
    font-size:20px;
  }
  .child_reference {
    text-align:center;
    display:block;
  }
  .page_title {
    margin-bottom:0;
  }
</style>

<div class="page_title">Facts</div>
<nav class="breadcrumbs">
  <div class="nav-wrapper">
    <div class=" col s12">
      <a href="{% url 'arvo:index' %}" class="breadcrumb">Outreach</a>
      <a href="{% url 'arvo:facts' %}" class="breadcrumb">Facts</a>
      {% if tag_name %}<a class="breadcrumb">{{tag_name}}</a>{% endif %}
    </div>
  </div>
</nav>
<ul class="children collapsible expandable">
  {% for child_reference in child_references %}
  <li>
    <a class="collapsible-header child_reference" href="/outreach/facts/{{child_reference.name}}/">{{child_reference.name}}</a>
  </li>
  {% endfor %}
</ul>


<ul class="collapsible expandable">
  {% for fact in facts %}
  <li>
    <div class="collapsible-header fact_header">
      <div class="fact_text">{{ fact.text }}</div>
      <div class="fact_button_bar">
        <i class="material-icons">expand_more</i>
      </div>

    </div>
    <div class="collapsible-body">
      <span>{{fact.extra_text}}</span>
      <div class="sources_title">Sources</div>
      <ul>
      {% for source in fact.sources.all %}
      <li><a href="{{source.url}}">{{source.title}}</a> - {{source.publication}}</li>
      {% endfor %}
    </div>
  </li>
  {% endfor %}
</ul>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.collapsible.expandable');
    var instances = M.Collapsible.init(elems, {
      accordion: false,
    });
  });

  let dont_expands = document.querySelectorAll('.dont_expand')
  for (let i=0; i<dont_expands.length; ++i) {
    dont_expands[i].onclick = function(e) {
      e.stopPropagation();
    }
  }
</script>


{% endblock %}

arvo/templates/arvo/index.html
{% extends 'main/base.html' %}
{% block title %}- Outreach{% endblock %}
{% block main %}
<style type="text/css">
  .collapsible-header {
    text-align:center;
    width:100%;
    height:100%;
    display:block;
    font-size:24px;
    margin-bottom:20px;
  }

</style>
<div class="page_title_center">Outreach</div>
<ul class="collapsible expandable">
  <li>
    <a href="/outreach/facts/" class="collapsible-header">facts</a>
  </li>
  <li>
    <a href="/outreach/responses/" class="collapsible-header">responses</a>
  </li>
  <li>
    <a href="/outreach/resources/" class="collapsible-header">resources</a>
  </li>
  <li>
    <a href="/outreach/codeofconduct/" class="collapsible-header">code of conduct</a>
  </li>
  <li>
    <a href="/govegan/" class="collapsible-header">go vegan</a>
  </li>
  <li>
    <a href="/outreach/about/" class="collapsible-header">about</a>
  </li>
</ul>

{% endblock %}

arvo/templates/arvo/resources.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} - Outreach - Resources{% endblock %}
{% block main %}
<style type="text/css">
  .resource_div {
    padding-left:10px;
  }
  .resource_div ul {
    padding-left:20px;
  }
  .resource_div li {
    font-size: 20px;
    margin:4px;
    
  }
</style>
<div class="page_title"><a href="{% url 'arvo:index' %}">Outreach</a> - Resources</div>
<div class="resource_div">
<h2>Outreach</h2>
<ul class="browser-default">
  <li><a href="https://www.amazingveganoutreach.com/learnonline">Amazing Vegan Outreach's web series</a></li>
  <li><a href="https://www.facebook.com/toni.dipianduni/videos/211704999602669/">Workshop by Amazing Vegan Outreach</a></li>
  <li><a href="https://www.facebook.com/naturallycheyenne/videos/346949579397813/">Workshop by Naturally Cheyenne</a></li>
  <li><a href="https://www.youtube.com/watch?v=ryzuXEI5wfU">Workshop by Marley Delgado</a></li>
  <li><a href="https://www.youtube.com/watch?v=PxCF_8sY54o">How to Talk to Non-Vegans - Earthling Ed</a></li>
  <li><a href="https://www.vegansociety.com/whats-new/blog/five-ways-maximise-your-outreach-non-vegans">Article by The Vegan Society</a></li>
</ul>
<h2>Responses</h2>
<ul class="browser-default">
  <li><a href="https://www.youtube.com/playlist?list=PL03LZR09P2gQJyBgHk_XE8gbj8j9uFs8G">Earthling Ed - 30 Days 30 Excuses</a>&nbsp;&nbsp;/&nbsp;&nbsp;<a href="https://earthlinged.org/ebook">ebook</a></li>
  <li><a href="https://yourveganfallacyis.com/en">Your Vegan Fallacy Is</a></li>
  <li><a href="https://www.carnismdebunked.com/">Carnism Dubunked</a></li>
  <li><a href="https://justiceforanimals.org/Replies_Listing">Justice For Animals - Replies</a></li>
  <li><a href="http://www.godfist.com/vegansidekick/guide.php">Vegan Sidekick Debate Guide</a></li>
  <li><a href="https://veganspeak.org/vegan-arguments/">Veganspeak - Vegan Arguments Guide</a></li>
</ul>
<h2>Leafleting</h2>
<ul class="browser-default">
  <li><a href="https://veganoutreach.org/leafleting-and-booklet-effectiveness/">Vegan Outreach - Leafleting and Booklet Effectiveness</a></li>
  <li><a href="https://www.peta.org/action/activism-guide/everyday-activism/leafleting/">PETA - Easy and Effective Leafleting</a>
</ul>
</div>
{% endblock %}

arvo/templates/arvo/responses.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} - Outreach - Responses{% endblock %}
{% block main %}
<style type="text/css">
  .collapsible li {
    margin-bottom:20px;
  }
  
  .collapsible-header {
    display:flex;
    flex-direction:row;
    justify-content:space-between;
    align-items:center;
  }
  
  .event_header_buttons {
    display:flex;
    flex-direction:column;
    justify-content:space-between;
  }
  
  .collapsible-body a {
    margin:10px;
  }
  
  .response_header_text {
    font-size:20px;
  }
  
  .collapsible li.active i.expand_icon {
    -ms-transform: rotate(180deg); /* IE 9 */
    -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
    transform: rotate(180deg);
  }
</style>
<div class="page_title"><a href="{% url 'arvo:index' %}">Outreach</a> - Responses</div>
<ul class="collapsible expandable">
  {% for response in responses %}
  <li>
    <div class="collapsible-header">
      <div class="response_header_text">{{ response.name }}</div>
      <div class="response_header_buttons">
        <i class="material-icons expand_icon">expand_more</i>
      </div>
    </div>
    <div class="collapsible-body">
      <span>{{response.description|safe}}</span>
    </div>
  </li>
  {% endfor %}
</ul>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.collapsible.expandable');
    var instances = M.Collapsible.init(elems, {
      accordion: false
    });
    
    let dont_expands = document.querySelectorAll('.dont_expand')
    for (let i=0; i<dont_expands.length; ++i) {
      dont_expands[i].onclick = function(e) {
        e.stopPropagation();
      }
    }
    
  });
</script>
{% endblock %}