activewiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('events/', include('events.urls')),
    path('facts/', include('facts.urls')),
    path('resources/', include('resources.urls')),
    path('users/', include('users.urls')),
    path('outreach/', include('arvo.urls')),
    path('badmin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

arvo/urls.py
from django.urls import path

from . import views

app_name = 'arvo'
urlpatterns = [
    path('', views.index, name='index'),
    path('facts/', views.facts, name='facts'),
    path('facts/<str:tag_name>/', views.facts, name='facts'),
    path('responses/', views.responses, name='responses'),
    path('resources/', views.resources, name='resources'),
    path('codeofconduct/', views.code_of_conduct, name='code_of_conduct'),
    path('about/', views.about, name='about')
]

events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new_event, name='new_event'),
    # path('edit/<int:event_id>/', views.edit_event, name='edit'),
    path('load_json/', views.load_json, name='load_json'),
    path('weekly_text_post/', views.weekly_text_post, name='weekly_text_post'),
    path('submit/', views.submit, name='submit'),
    path('<int:event_id>/', views.detail, name='detail'),
    path('<str:paths>/', views.index, name='paths')
]

events/models.py
from django.contrib.auth.models import User
from django.db import models
from users.models import User
from django.forms import ModelForm

import os

from main.models import Tag, SubmissionStatus, Subdomain, Cause



class EventTag(models.Model):
    display_name = models.CharField(max_length=200)
    path_name = models.CharField(max_length=200)
    parent_tag = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, related_name='child_tags')

    def __str__(self):
        return self.display_name



class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField(null=True, blank=True)
    address = models.CharField(max_length=500)
    hosts = models.CharField(max_length=500)
    url = models.CharField(max_length=500)
    submission_status = models.ForeignKey(SubmissionStatus, on_delete=models.PROTECT, related_name='events')
    subdomains = models.ManyToManyField(Subdomain, related_name='events', blank=True)
    tags = models.ManyToManyField(EventTag, related_name='events', blank=True)
    causes = models.ManyToManyField(Cause, related_name='events')
    submitted_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='events', null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    edited_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        r = ''
        # if self.tags.count() == 0:
        #     r += 'tagless - '
        return r + self.submission_status.name + ' - ' + self.title

    def pretty_datetime(self):

        if os.name == 'nt':
            dtf = '%A %#m/%#d %#I:%M %p'
            tf = '%#I:%M %p'
        else:
            dtf = '%A %-m/%-d %-I:%M %p'
            tf = '%-I:%M %p'

        sdt = self.start_datetime
        # sdt = timezone.localtime(sdt, pytz.timezone('US/Pacific'))

        edt = self.end_datetime
        if edt is None:
            return sdt.strftime(dtf)
        else:
            # edt = timezone.localtime(edt, pytz.timezone('US/Pacific'))
            if sdt.year == edt.year \
                and sdt.month == edt.month \
                and sdt.day == edt.day:
                return sdt.strftime(dtf) \
                        + ' - ' + edt.strftime(tf)
            return sdt.strftime(dtf) \
                + ' - ' + edt.strftime(dtf)

    def toDictionary(self):
        return {
            'title': self.title,
            'description': self.description,
            'hosts': self.hosts,
            'url': self.url,
            'datetime': self.pretty_datetime(),
            'location': self.location
        }

events/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator

from activewiki import secrets

import datetime
import requests
import json

from main import parameter_parser


from events.models import Event, EventTag
from main.models import SubmissionStatus, Subdomain, Cause
from users.models import User


def get_week_dates(index):
    today = datetime.datetime.now().date()
    current_week_start = today - datetime.timedelta(days=today.weekday())
    week_start = current_week_start + datetime.timedelta(days=7*index)
    week_end = current_week_start + datetime.timedelta(days=7*index+6)
    return week_start, week_end

@login_required
def weekly_text_post(request):
    weeks = []
    for i in range(-2, 3):
        week_start, week_end = get_week_dates(i)
        weeks.append({
            'index': i,
            'name': week_start.strftime('%m/%d') + ' - ' + week_end.strftime('%m/%d')
        })
    week_index = 1 if request.method != 'POST' else int(request.POST['week_index'])
    week_start, week_end = get_week_dates(week_index)
    week_end += datetime.timedelta(days=1)
    approved_status = SubmissionStatus.objects.get(name='approved')
    events = Event.objects.filter(submission_status_id=approved_status.id).order_by('start_datetime')
    events = events.filter(end_datetime__gte=week_start)
    events = events.filter(start_datetime__lte=week_end)
    return render(request, 'events/weekly_text_post.html', {'weeks': weeks, 'events': events, 'week_index': week_index})

@login_required
def load_json(request):
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('main:index'))
    if request.method == 'POST':
        json_events = request.POST['json_events']
        data_events = json.loads(json_events)
        for data_event in data_events:
            if Event.objects.filter(url=data_event['url']).exists():
                continue
            format = "%Y-%m-%d %H:%M:%S"
            data_event['start_datetime'] = datetime.datetime.strptime(data_event['start_datetime'], format)
            if data_event['end_datetime'] == '':
                data_event['end_datetime'] = None
            else:
                data_event['end_datetime'] = datetime.datetime.strptime(data_event['end_datetime'], format)
            data_event['submission_status'] = SubmissionStatus.objects.get(name='pending')
            data_event['submitted_by'] = User.objects.get(username='flux')
            event = Event(**data_event)
            event.save()
    return render(request, 'events/load_json.html', {})



def index(request, paths=''):

    params = parameter_parser.parse_parameters(request.META, request.GET, paths, EventTag)
    subdomain = params['subdomain']
    page = params['page']
    start_date = params['start_date']
    if start_date is None:
        start_date = datetime.date.today()
    end_date = params['end_date']
    if end_date is not None:
        end_date += datetime.timedelta(days=1)
    selected_cause = params['cause']
    selected_tag = params['tag']



    approved_status = SubmissionStatus.objects.get(name='approved')
    events = None
    if subdomain is None:
        events = Event.objects.all()
    else:
        events = subdomain.events.all()
    events = events.filter(submission_status_id=approved_status.id)



    # filter by date
    # TODO FIX SO IT DOESN"T REMOVE EVENTS WHOSE END DATES ARE NULL
    # events_with_end_dates = events.filter(end_datetime__isnull=False)
    # events_with_end_times = events.filter(end_datetime__gte=start_date)
    # events_without_end_times = events.filter(end_datetime__isnull=True)
    events = events.filter(end_datetime__gte=start_date)
    if end_date is not None:
        events = events.filter(start_datetime__lte=end_date)

    # filter by cause
    if selected_cause is not None:
        events = events.filter(causes__in=[selected_cause.id])

    # filter by tag
    if selected_tag is not None:
        events = events.filter(tags__in=[selected_tag.id])

    # order by start date
    events = events.order_by('start_datetime')

    # split into pags
    events_per_page = 20
    paginator = Paginator(events, events_per_page)
    events_on_page = paginator.page(page)

    tags = EventTag.objects.order_by('display_name')
    causes = Cause.objects.order_by('name')

    data = {
        'data_type': 'events',
        'data_type_singular': 'event',
        'selected_tag': selected_tag,
        'selected_cause': selected_cause,
        'tags': tags,
        'causes': causes,
        'objects': events_on_page,
        'subdomain': subdomain,
        'subdomains': Subdomain.objects.order_by('name')
    }
    # return render(request, 'events/index.html', data)
    return render(request, 'main/data_list.html', data)




def detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    return render(request, 'events/detail.html', {'event': event})


def submit(request):

    if request.method == 'POST':
        if not request.user.is_superuser:
            recaptcha_response = request.POST.get('g-recaptcha-response')
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data = {
                'secret': secrets.google_recaptcha_key,
                'response': recaptcha_response
            })
            result = r.json()
            if not result['success']:
                return render(request, 'app/submit_facebook_event.html', {'message_error':'Invalid reCAPTCHA!'})


        params = request.POST
        id = params['id']
        title = params['title']
        description = params['description']
        hosts = params['hosts']
        address = params['address']
        start_date = params['start_date']
        start_time = params['start_time']
        end_date = params['end_date']
        end_time = params['end_time']
        url = params['url']
        tag_ids = params.getlist('tags')

        # if new or address has changed, use geocoding
        if id != '':
            event = Event.objects.get(pk=id)
        else:
            event = Event()

        event.title = title
        event.description = description
        event.hosts = hosts
        event.address = address

        # set the submission status to pending by default
        # even if it was already approved
        submission_status = None
        if request.user.is_superuser:
            submission_status_id = request.POST['submission_status_id']
            event.submission_status = get_object_or_404(SubmissionStatus, id=submission_status_id)
        else:
            submission_status, created = SubmissionStatus.objects.get_or_create(name='pending')
            event.submission_status = submission_status

        event.start_datetime = datetime.datetime.strptime(start_date + ' ' + start_time, '%b %d, %Y %I:%M %p')
        event.end_datetime = datetime.datetime.strptime(end_date + ' ' + end_time, '%b %d, %Y %I:%M %p')

        event.url = url
        event.save()

        event.tags.clear()
        for tag_id in tag_ids:
            event_tag = EventTag.objects.get(id=tag_id)
            event.tags.add(event_tag)


        messages.add_message(request, messages.INFO, 'Event Submitted Successfully')


    tags = EventTag.objects.order_by('display_name')
    submission_statuses = SubmissionStatus.objects.order_by('name')
    context = {
        'tags': tags,
        'submission_statuses': submission_statuses,
    }
    return render(request, 'events/submit.html', context)


@login_required
def new_event(request):
    tags = EventTag.objects.order_by('display_name')
    submission_statuses = SubmissionStatus.objects.order_by('name')
    context = {
        'tags': tags,
        'submission_statuses': submission_statuses
    }
    return render(request, 'events/detail.html', context)

@login_required
def edit_event(request, event_id):
    tags = EventTag.objects.order_by('name')
    submission_statuses = SubmissionStatus.objects.order_by('name')
    event = get_object_or_404(Event, id=event_id)
    if not request.user.is_superuser and event.submitted_by.id != request.user.id:
        raise Http404
    context = {
        'tags': tags,
        'submission_statuses': submission_statuses,
        'event': event
    }
    return render(request, 'events/detail.html', context)

events/templates/events/detail.html
{% extends 'main/base.html' %}
{% block title %} - {{event.title}}{% endblock %}
{% block main %}
<style type="text/css">

  .object {

  }
  .object > * {
    margin-top:8px;
    padding:20px;
    background-color: var(--foreground-color);
    font-size:18px;
  }
  .object_title {
    font-size:32px;
  }
</style>
<div class="object">
  <div class="object_title">{{ event.title }}</div>
  <div class="">
    <div>Hosted by {{event.hosts}}</div>
    <div>{{event.pretty_datetime}}</div>
    <div>{{event.address}}</div>
  </div>
  <div>
    {{event.description | safe}}
  </div>
  <div>
    <a href="{{event.url}}" class="btn">More Info</a>
    <a href="{% url 'events:index' %}" class="btn">View More Events</a>
  </div>

</div>

{% endblock %}

events/templates/events/item.html
<div class="collapsible-header">
  <div class="object_text">
    <div class="title" title="{{object.id}}">{{ event.title }}</div>
    <ul class="browser-default">
      <li>Hosted by {{event.hosts}}</li>
      <li>{{event.pretty_datetime}}</li>
      <li>{{event.address}}</li>
    </ul>
    <div class="tag_expand_bar">
      {% include 'main/tags.html' with tags=event.tags.all causes=event.causes.all %}
    </div>
  </div>
  <div class="object_buttons">
    <a class="dropdown-trigger dont_expand" data-target="dropdown{{index}}"><i class="material-icons main_object_icon">share</i></a>
    <ul id='dropdown{{index}}' class='dropdown-content'>
      <li><a class="dont_expand" onclick="copyEventLink{{index}}()">Copy Link</a></li>
      <li><a class="dont_expand" onclick="copyEventText{{index}}()">Copy Text</a></li>
      <li><a class="dont_expand" onclick="shareEventEmail{{index}}()">Share by Email</a></li>
      <li><a class="dont_expand" onclick="shareEventFacebook{{index}}()">Share on Facebook</a></li>
      <li><a class="dont_expand" onclick="shareEventTwitter{{index}}()">Share on Twitter</a></li>
    </ul>
    <script type="text/javascript">
      function copyEventLink{{index}}() {
        copyToClipboard(window.location.host+'/{{data_type}}/{{object.id}}/')
      }
      function copyEventText{{index}}() {
        let text = document.title + ' ' + window.location.href + '\n'
        text += '-----------------------\n'
        text += '{{object.title}}\n'
        text += 'Hosted by {{object.hosts}}\n'
        text += '{{object.pretty_datetime}}\n'
        text += '{{object.address}}\n'
        text += window.location.host+'/{{data_type}}/{{object.id}}/\n'
        copyToClipboard(text)
      }
      function shareEventEmail{{index}}() {
        let subject = document.title
        let body = window.location.host+'/{{data_type}}/{{object.id}}/'
        window.location.href = 'mailto:?subject='+encodeURI(subject)+'&body='+encodeURI(body)
      }
      function shareEventFacebook{{index}}() {
        text = window.location.href
        window.location.href = 'https://www.facebook.com/sharer/sharer.php?u=' + encodeURI(text)
      }
      function shareEventTwitter{{index}}() {
        let text = document.title
        let url = window.location.host+"/{{data_type}}/{{object.id}}/"
        window.location.href = 'https://twitter.com/intent/tweet?text=' + encodeURI(text) + '&url=' + encodeURI(url)
      }
    </script>
    <a href="{{object.url}}" class="dont_expand"><i class="material-icons">link</i></a>
    <a><i class="material-icons expand_icon main_object_icon">expand_more</i></a>
  </div>
</div>
<div class="collapsible-body">
  <span>{{object.description | safe}}</span>
</div>

events/templates/events/load_json.html
{% extends 'main/base.html' %}
{% block title %} - Load events from JSON{% endblock %}
{% block main %}
<div class="page_title">Load events from JSON</div>
<form action="" method="post">
  {% csrf_token %}
  <button class="btn">submit</button>
  <div class="input-field">
    <textarea id="json_events" name="json_events" class="materialize-textarea"></textarea>
    <label for="json_events">JSON</label>
  </div>
</form>
{% endblock %}

events/templates/events/submit.html
{% extends 'main/base.html' %}
{% block title %} - Submit Event{% endblock %}
{% block main %}

<script src='https://www.google.com/recaptcha/api.js'></script>




<style type="text/css">
  h2 {
    margin: 10px;
  }

  /* Inactive/Active Default input field color */
  /*.input-field input[type]:not([readonly]),
  .input-field input[type]:focus:not([readonly]),
  .input-field textarea:not([readonly]),
  .input-field textarea:focus:not([readonly]) {
      border-bottom: 1px solid #b3e5fc;
      /*box-shadow: 0 1px 0 0 #b3e5fc;*
  }*/

  /* Inactive/Active Default input label color */
  .input-field input[type]:focus:not([readonly])+label,
  .input-field textarea:focus:not([readonly])+label {
    color: #b3e5fc;
  }

  /* Active/Inactive Invalid input field colors */
  /*.input-field input[type].invalid,
  .input-field input[type].invalid:focus,
  .input-field textarea.invalid,
  .input-field textarea.invalid:focus {
      border-bottom: 1px solid #7986cb;
      box-shadow: 0 1px 0 0 #7986cb;
  }*/

  /* Active/Inactive Invalid input label color */
  .input-field input[type].invalid:focus+label,
  .input-field input[type].invalid~.helper-text::after,
  .input-field input[type].invalid:focus~.helper-text::after,
  .input-field textarea.invalid:focus+label,
  .input-field textarea.invalid~.helper-text::after,
  .input-field textarea.invalid:focus~.helper-text::after {
    color: #7986cb;
  }

  /* Active/Inactive Valid input field color */
  /*.input-field input[type].valid,
  .input-field input[type].valid:focus,
  .input-field textarea.valid,
  .input-field textarea.valid:focus {
      border-bottom: 1px solid #b3e5fc;
      box-shadow: 0 1px 0 0 #b3e5fc;
  }*/

  /* Active/Inactive Valid input label color */
  .input-field input[type].valid:focus+label,
  .input-field input[type].valid~.helper-text::after,
  .input-field input[type].valid:focus~.helper-text::after,
  .input-field textarea.valid:focus+label,
  .input-field textarea.valid~.helper-text::after,
  .input-field textarea.valid:focus~.helper-text::after {
    color: #b3e5fc;
  }



  /*.picker__date-display { background-color: #6d4e7a; }
  .picker__day.picker__day--today { color: red; }
  .picker__day--selected, .picker__day--selected:hover, .picker--focused .picker__day--selected { background-color: #6d4e7a;}
  .picker__close { color: #6d4e7a !important;}
  .picker__today { color: #6d4e7a !important;}
  .clockpicker-tick:hover { background: #6d4e7a !important; }
  .clockpicker-canvas line { stroke: #6d4e7a !important; }
  .clockpicker-canvas-bearing { fill: #6d4e7a !important; }
  .clockpicker-canvas-bg { fill: #6d4e7a !important; }*/
</style>
<div class="main_container">
  <div class="page_title">Submit Event</div>
  <div class="row">
    <form action="{% url 'events:submit' %}" method="post" class="col s12">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{event.id}}" />
      <div class="row">
        <div class="input-field col s12">
          <input id="title" name="title" value="{{event.title}}" type="text" class="validate">
          <label for="title">Title</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea id="description" name="description" class="materialize-textarea" class="validate">{{event.description}}</textarea>
          <label for="description">Description</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="address" name="address" value="{{event.address}}" type="text" class="validate">
          <label for="address">Address</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="hosts" name="hosts" value="{{event.hosts}}" type="text" class="validate">
          <label for="hosts">Host(s)</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s6">

          <input id="start_date" name="start_date" type="text" class="validate datepicker" value="{{event.start_datetime|date:'M d, Y'}}">
          <label for="start_date">Start Date</label>
        </div>
        <div class="input-field col s6">
          <input id="start_time" name="start_time" type="text" class="validate timepicker" value="{{event.start_datetime|time:'h:i A'}}">
          <label for="start_time">Start Time</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input id="end_date" name="end_date" type="text" class="validate datepicker" value="{{event.end_datetime|date:'M d, Y'}}">
          <label for="end_date">End Date</label>
        </div>
        <div class="input-field col s6">
          <input id="end_time" name="end_time" type="text" class="validate timepicker" value="{{event.end_datetime|time:'h:i A'}}">
          <label for="end_time">End Time</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="url" name="url" value="{{event.url}}" type="text" class="validate">
          <label for="url">Url</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <select id="tags" name="tags" multiple>
            {% for tag in tags %}
            <option value="{{tag.id}}" {% if tag in event.tags.all %}selected{% endif %}>{{tag.display_name}}</option>
            {% endfor %}
          </select>
          <label for="tags">Tags</label>
        </div>
      </div>
      {% if user.is_superuser %}
      <div class="row">
        <div class="input-field col s12">
          <select id="submission_status" name="submission_status_id">
            {% for submission_status in submission_statuses %}
            <option value="{{submission_status.id}}" {% if submission_status.id in event.submission_status.id %}selected{% endif %}>{{submission_status.name}}</option>
            {% endfor %}
          </select>
          <label for="submission_status">Submission Status</label>
        </div>
      </div>
      {% else %}
      <div class="input-field">
        <div class="g-recaptcha" data-sitekey="6LemOMIUAAAAAG6fsfOflyOHWQvASTGdKoORV0o_"></div>
      </div>
      {% endif %}
      <button type="submit" class="btn">Submit</button>
    </form>
  </div>
</div>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var datepicker_elements = document.querySelectorAll('.datepicker');
    var datepicker_instances = M.Datepicker.init(datepicker_elements, {
      showClearBtn: true
    });

    let timepicker_elements = document.querySelectorAll('.timepicker');
    let timepicker_instances = M.Timepicker.init(timepicker_elements, {
      showClearBtn: true
    });

    let selects = document.querySelectorAll('select');
    let select_instances = M.FormSelect.init(selects, {
      'isMultiple': true
    });
  });
</script>
{% endblock %}

events/templates/events/weekly_text_post.html
{% extends 'main/base.html' %}
{% block title %} - event post{% endblock %}
{% block main %}
<style>
    textarea {
        height: 400px;
        padding:10px;
    }

    #formdiv {
        padding:10px;
        margin:10px 0px;
        text-align:center;
    }

</style>
<div id="formdiv" class="row">
    <form action="" method="post">
        {% csrf_token %}
        <div class="input-field inline">
            <select name="week_index" class="inline">
                {% for week in weeks %}
                <option value="{{week.index}}" {% if week.index == week_index %}selected{% endif %}>{{week.name}}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn">view events</button>
    </form>
</div>
<textarea>
Here are the upcoming events for the week, view more at http://pdx.activewiki.org/events/
{% for event in events %}
{{event.title}}
{{event.pretty_datetime}}
{{event.address}}
{{event.url}}
--------------------------
{% endfor %}
</textarea>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, {});
    });
</script>

{% endblock %}