activewiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('events/', include('events.urls')),
    path('facts/', include('facts.urls')),
    path('resources/', include('resources.urls')),
    path('users/', include('users.urls')),
    path('outreach/', include('arvo.urls')),
    path('badmin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

arvo/urls.py
from django.urls import path

from . import views

app_name = 'arvo'
urlpatterns = [
    path('', views.index, name='index'),
    path('facts/', views.facts, name='facts'),
    path('facts/<str:tag_name>/', views.facts, name='facts'),
    path('responses/', views.responses, name='responses'),
    path('resources/', views.resources, name='resources'),
    path('codeofconduct/', views.code_of_conduct, name='code_of_conduct'),
    path('about/', views.about, name='about')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('register_user/', views.register_user, name='register_user'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('home/', views.home, name='home'),
    path('newsletter/', views.user_newsletter, name='user_newsletter'),
    path('newsletter/<str:code>/', views.user_newsletter, name='user_newsletter_code'),
    path('send_newsletter/', views.send_newsletter, name='send_newsletter')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    location = models.CharField(max_length=50, blank=True)


class NewsletterSubscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, related_name="newsletter_signup", null=True, blank=True)
    email_address = models.CharField(max_length=200)
    code = models.CharField(max_length=20)
    date_code = models.DateTimeField(null=True, blank=True)
    date_last_message = models.DateTimeField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email_address

users/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect



from .models import User

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from main import parameter_parser


def user_newsletter(request, code=''):
    user = request.user
    newsletter_signup = user.newsletter_signup if user.is_authenticated else None
    if newsletter_signup is None:
        newsletter_signup = NewsletterSignup.objects.filter(code=code, date_code__gte=datetime.now()-datetime.timedelta(days=7)).first()
    subdomain = parameter_parser.get_subdomain(request.META)
    context = {
        'newsletter_signup': newsletter_signup,
        'subdomain': subdomain,
    }
    return render(request, 'users/newsletter.html', context)


def send_newsletter(request):
    newsletter_subscriptions = NewsletterSubscription.objects.all()
    # for newsletter_subscription in newsletter_subscriptions:
        
        
    


def login_page(request):
    
    message = request.GET.get('m', '')
    next = request.GET.get('next', '')
    
    context = {
        'message': message,
        'next': next
    }
    return render(request, 'users/login.html', context)


def register_user(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    next = request.POST['next']
    
    user = User.objects.create_user(username, email, password)
    login(request, user)
    
    if next != '':
        return HttpResponseRedirect(next)
    return HttpResponseRedirect(reverse('users:protected'))


def login_user(request):
    username = request.POST['username']
    password = request.POST['password']
    next = request.POST['next']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if next != '':
            return HttpResponseRedirect(next)
        return HttpResponseRedirect(reverse('users:protected'))
    if next != '':
        return HttpResponseRedirect(reverse('users:register_login')+'?m=1&next='+next)
    return HttpResponseRedirect(reverse('users:register_login')+'?m=1')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:register_login')+'?m=2')

def home(request):
    # TODO: render user home, their submitted events
    return render(request, 'users/home.html', {})

users/templates/users/home.html
{% extends 'main/base.html' %}
{% block title %}home{% endblock %}
{% block main %}
<h1>User Home</h1>
{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}
{% block title %}login{% endblock %}
{% block main %}
{% if message == 1 %}
<div style="background-color:red;color:white;">Your username and password did not match</div>
{% elif message == 2 %}
<div style="background-color:blue;color:white;">You have successfully logged out</div>
{% endif %}
<h1>Login</h1>
<form action="{% url 'users:login_user' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{next}}"/>
  <input type="text" name="username" placeholder="username"/>
  <input type="password" name="password" placeholder="password"/>
  <button type="submit">Login</button>
</form>
{% endblock %}

users/templates/users/newsletter.html
{% extends 'main/base.html' %}

{% block title %} - Newsletter Subscription{% endblock %}

{% block content %}

<div class="page_title">
  {% if newsletter_subscription %}Edit Newsletter Subscription{% else %}Subscribe to the Newsletter{% endif %}
</div>
{% if newsletter_subscription %}
  <div>{{newsletter_subscription.email}}"</div>
{% else %}
  <a class="btn">Edit Existing Subscription</a>
{% endif %}
{% if message_type == 'already_exists' %}
<div>A subscription at that email address already exists, a link to edit your subscription has been sent.</div>
{% endif %}
<input type="hidden" name="code" value={{newsletter_subscription.code}}>
<select multiple>
  {% for subdomain in subdomains %}
  <option value="{{subdomain.id}}">{{subdomain.name}}</option>
  {% endfor %}
</select>
{% if newsletter_subscription %}<button type="submit" class="btn">Unsubscribe</button>{% endif %}
<button type="submit" class="btn">Save</button>
recaptcha
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}
{% block title %}login{% endblock %}
{% block main %}
<h1>Register</h1>
<form action="{% url 'users:register_user' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{next}}"/>
  <input type="text" name="username" placeholder="username" required pattern="\w{3,15}" title="username must be between 3 and 15 characters, all lowercase"/>
  <input type="text" name="email" placeholder="email" required pattern="\w+@\w+\.\w+" title="please enter a properly formatted email address"/>
  <input type="password" id="input_password" name="password" placeholder="password"/>
  <input type="password" id="input_password2" name="password2" placeholder="retype password"/>
  <button type="submit" id="bt_register">Register</button>
</form>

<script type="text/javascript">
  bt_register = document.querySelector('#bt_register')
  input_password = document.querySelector('#input_password')
  input_password2 = document.querySelector('#input_password2')
  
  bt_register.onclick = function(evt) {
    if (input_password.value != input_password2.value) {
      alert('those passwords do not match')
      evt.preventDefault()
    }
  }
</script>
{% endblock %}