activewiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('events/', include('events.urls')),
    path('facts/', include('facts.urls')),
    path('resources/', include('resources.urls')),
    path('users/', include('users.urls')),
    path('outreach/', include('arvo.urls')),
    path('badmin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

arvo/urls.py
from django.urls import path

from . import views

app_name = 'arvo'
urlpatterns = [
    path('', views.index, name='index'),
    path('facts/', views.facts, name='facts'),
    path('facts/<str:tag_name>/', views.facts, name='facts'),
    path('responses/', views.responses, name='responses'),
    path('resources/', views.resources, name='resources'),
    path('codeofconduct/', views.code_of_conduct, name='code_of_conduct'),
    path('about/', views.about, name='about')
]

main/urls.py
from django.urls import path

from . import views
import users.views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('govegan/', views.govegan, name='govegan'),
    path('getactive/', views.getactive, name='getactive'),
    path('about/', views.about, name='about'),
    path('vegen/', views.vegen, name='vegen'),
    path('newsletter/', users.views.user_newsletter, name='newsletter'),
    path('aapdx/', views.aapdx, name='aapdx'),
    path('<str:path1>/', views.other, name='other'),
    path('<str:path1>/<str:path2>/', views.other, name='other'),
]

main/models.py
from django.db import models

from users.models import User


# class PathHitCount(models.Model):
#     path = models.CharField(max_length=200)
#     count = models.IntegerField()
#     datetime_created = models.DateTimeField(auto_now_add=True)
# 
#     def __str__(self):
#         return self.datetime_created.strftime('%Y-%m-%d') + ' ' + str(self.count)



class LinkType(models.Model):
    name = models.CharField(max_length=200)
    icon = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name


class TagType(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(TagType, on_delete=models.PROTECT, related_name='tags', null=True)
    
    def __str__(self):
        return self.type.name + ' - ' + self.name
    
    class Meta:
        ordering = ['name']

class SubmissionStatus(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

class PathRedirect(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=500)
    
    def __str__(self):
        return self.name

class SubdomainTheme(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

class Subdomain(models.Model):
    name = models.CharField(max_length=40) # appears in <title> and nav bar, e.g. Portland, Oregon
    subdomain = models.CharField(max_length=40) # for the subdomain, e.g. pdx.activewiki.org
    theme = models.ForeignKey(SubdomainTheme, on_delete=models.PROTECT, related_name='themes')
    tags = models.ManyToManyField(Tag, blank=True, related_name='subdomains')
    distance_units = models.CharField(max_length=10)
    distance = models.FloatField()
    address = models.CharField(max_length=200) # e.g. Portland, Oregon, USA
    latitude = models.FloatField()
    longitude = models.FloatField()
    
    def __str__(self):
        return self.name



class Cause(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
    

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.paginator import Paginator


from main import parameter_parser
from main.models import Subdomain, SubmissionStatus
from .models import PathRedirect
from groups.models import Group, GroupTag, GroupType

import groups.views


from events.models import Event
import datetime


def index(request):
    links = ['events', 'organizations', 'communities', 'sanctuaries', 'facts', 'resources', 'outreach']
    return render(request, 'main/index.html', {'links': links})

def about(request):
    return render(request, 'main/about.html')

def vegen(request):
    return render(request, 'main/vegen.html')

def govegan(request):
    subdomain = parameter_parser.get_subdomain(request.META)
    context = {
        'subdomain': subdomain
    }
    return render(request, 'main/go_vegan.html', context)

def getactive(request):
    subdomain = parameter_parser.get_subdomain(request.META)
    return render(request, 'main/get_active.html')


def aapdx(request):
    start_date = datetime.date.today()
    events = Event.objects.filter(submission_status__name='approved', subdomains__subdomain='pdx', start_datetime__gte=start_date, causes__name='animals')
    events = events.order_by('start_datetime')
    page = request.GET.get('page', 1)
    events_per_page = 20
    paginator = Paginator(events, events_per_page)
    events = paginator.page(page)
    context = {
        'events': events
    }
    return render(request, 'main/aapdx.html', context)


def cause(request, cause_name):
    context = {
        'cause_name': cause_name
    }
    return render(request, 'main/cause.html', context)


def other(request, path1, path2=''):
    if path1 in ['animals', 'environment', 'humans']:
        return cause(request, path1)
    elif path1 in ['organizations', 'communities', 'sanctuaries']:
        if path2 == '':
            group_type = GroupType.objects.get(name=path1)
            return groups.views.index(request, group_type, '')
        elif path2.isdigit():
            group_id = int(path2)
            return groups.views.detail(request, group_id)
        elif path2 == 'submit':
            return groups.views.submit(request, path1)
        else:
            group_type = GroupType.objects.get(name=path1)
            return groups.views.index(request, group_type, path2)
    raise Http404

main/templates/main/aapdx.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Animal Activism PDX</title>

  <!-- https://materializecss.com/ -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

  <!-- https://vuejs.org/ -->
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

  <!-- https://github.com/axios/axios -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>




  <style>
    * {
      box-sizing: border-box;
    }

    body {
      font-family: 'Open Sans', sans-serif;
      scroll-behavior: smooth;
    }

    #title_long {
      display: none;
      white-space: nowrap;
    }

    #title_short {
      white-space: nowrap;
    }

    @media only screen and (min-width: 800px) {
      #maincontainer {
        width: 800px;
        margin: 0 auto;
      }

      #title_short {
        display: none;
      }

      #title_long {
        display: inherit;
      }
    }
  </style>



  <style>
    #event_list {
      display: flex;
      flex-direction: column;
      margin: 0 auto;
    }

    #event_list > div {
      margin-top: 20px;
      transition: all ease 0.2s;
      /*box-shadow: 0px 2px 2px lightgrey;*/
      cursor: pointer;
    }

    #event_list ul {
      margin: 0;
    }

    .event_title {
      font-size: 26px;
    }

    #pages>span {
      margin: 4px;
      cursor: pointer;
      padding: 4px;
    }

    .collapsible-header {
      display: flex;
      flex-direction: column;
    }
    .collapsible-header ul {
        font-size:18px;
        padding-left:20px;
    }

    .list_element>li {
      margin: 0 0 20px 0 !important;
      width: 100% !important;
    }


    @media only screen and (min-width: 800px) {
      #filters {
        display: flex;
        flex-direction: row;
        width: 100%;
      }

      #filters>div {
        width: 33%;
        padding: 10px;
      }
    }

    .pagination {
      text-align: center;
    }

    .list_element li.active i {
      -ms-transform: rotate(180deg);
      /* IE 9 */
      -webkit-transform: rotate(180deg);
      /* Chrome, Safari, Opera */
      transform: rotate(180deg);
    }


    /* .event_expand_bt {
          display:table;
          height:100%;
        }
        .event_expand_bt > * {
          text-align:right;
          vertical-align: middle;
          display:table-cell;
        } */

    .event_expand_bt i {
      margin: 0;
    }

    .flex_column {
      display: flex;
      flex-direction: column;
    }

    /* #filters select, #filters input {
          background-color:white;
          padding:8px;
          color:black;
        } */


    #filters>div {
      background-color: white;
      margin: 4px;
    }

    #awiki_message {
      text-align: center;
      margin: 20px 0;
      padding: 10px;
      font-size: 20px;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    #awiki_message > * {
      margin:0 10px;
    }
    .collapsible-body {
      background-color:white;
    }
  </style>
</head>

<body class="green lighten-4">
  <div id="maincontainer">
    <nav class="green">
      <div class="nav-wrapper">
        <a href="{% url 'main:aapdx' %}" id="title_short" class="brand-logo center">AAPDX</a>
        <a href="{% url 'main:aapdx' %}" id="title_long" class="brand-logo center">Animal Activism PDX</a>
      </div>
    </nav>
    <a href="http://pdx.activewiki.org/events/animals/">
      <div id="awiki_message" class="green white-text">
        <i class="material-icons">keyboard_arrow_right</i>
        <div>aapdx.org is now part of activewiki.org - click to more info</div>
        <i class="material-icons">keyboard_arrow_left</i>
      </div>
    </a>

    <div id="event_list">
      {% if events %}
      <ul class="collapsible popout list_element">
        {% for event in events %}
        <li>
          <div class="collapsible-header">
            <div style="display:flex;flex-direction:row;justify-content: space-between;">
              <div class="flex_column">
                <div class="event_title" title="{{event.id}}">{{ event.title }}</div>
                <ul class="browser-default">
                  <li>Hosted by {{event.hosts}}</li>
                  <li>{{event.pretty_datetime}}</li>
                  <li>{{event.address}}</li>
                </ul>
              </div>
              <div class="flex_column" style="justify-content: space-between;">
                <div class="event_expand_bt">
                  <a class="green-text dont_expand" href="{{event.url}}">
                    <i class="material-icons">link</i>
                  </a>
                </div>
                <div class="event_expand_bt" style="">
                  <div class="green-text">
                    <i class="material-icons">expand_more</i>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="collapsible-body">
            <span>{{event.description | safe}}</span>
          </div>
        </li>
        {% endfor %}
      </ul>

      {% else %}
      <div style="text-align:center" class="white">no events to display</div>
      {% endif %}
    </div>

    {% include 'main/pagination.html' with objects=events %}

    <script>
      document.addEventListener('DOMContentLoaded', function() {

        var uls = document.querySelectorAll('.collapsible');
        var ul_instances = M.Collapsible.init(uls, {});
      });
    </script>
  </div>
  <script>
    let symbols = {
      // 'leaf_left': '☙',
      // 'flower': '⚘',
      'seedling': '🌱',
      'evergreen_tree': '🌲',
      'deciduous_tree': '🌳',
      // 'palm_tree': '🌴',
      'cactus': '🌵',
      // 'tulip': '🌷',
      // 'cherry_blossom': '🌸',
      'rose': '🌹',
      // 'hibiscus': '🌺',
      'sunflower': '🌻',
      // 'blossom': '🌼',
      'herb': '🌿',
      'four_leaf_clover': '🍀',
      'maple_leaf': '🍁',
      'fallen_leaf': '🍂',
      // //'leaf_fluttering_in_wind': '🍃',
      // 'tomato': '🍅',
      // 'aubergine': '🍆',
      // 'grapes': '🍇',
      // 'melon': '🍈',
      // 'watermelon': '🍉',
      // 'tangerine': '🍊',
      // 'lemon': '🍋',
      // 'banana': '🍌',
      // 'pineapple': '🍍',
      // 'red_apple': '🍎',
      // 'green_apple': '🍏',
      // 'pear': '🍐',
      // 'peach': '🍑',
      // 'cherries': '🍒',
      // 'strawberry': '🍓',
      // //'boquet': '💐',
      // 'white_flower': '💮',

      // 'white chess knight': '♘',
      // 'black chess knight': '♞',
      'rat': '🐀',
      'mouse': '🐁',
      'ox': '🐂',
      'water buffalo': '🐃',
      'cow': '🐄',
      'tiger': '🐅',
      'leopard': '🐆',
      'rabbit': '🐇',
      'cat': '🐈',
      //'dragon': '🐉',
      'crocodile': '🐊',
      'whale': '🐋',
      'snail': '🐌',
      'snake': '🐍',
      'horse': '🐎',
      'ram': '🐏',
      'goat': '🐐',
      'sheep': '🐑',
      'monkey': '🐒',
      'rooster': '🐓',
      'chicken': '🐔',
      'dog': '🐕',
      'pig': '🐖',
      'boar': '🐗',
      'elephant': '🐘',
      'octopus': '🐙',
      'spiral shell': '🐚',
      'bug': '🐛',
      'ant': '🐜',
      'honeybee': '🐝',
      'lady beetle': '🐞',
      'fish': '🐟',
      'tropical fish': '🐠',
      'blowfish': '🐡',
      'turtle': '🐢',
      'hatching chick': '🐣',
      'baby chick': '🐤',
      'front-facing baby chick': '🐥',
      'bird': '🐦',
      'penguin': '🐧',
      'koala': '🐨',
      'poodle': '🐩',
      'dromedary camel': '🐪',
      'bactrian camel': '🐫',
      'dolphin': '🐬',
      'mouse face': '🐭',
      'cow face': '🐮',
      'tiger face': '🐯',
      'rabbit face': '🐰',
      'cat face': '🐱',
      //'dragon face': '🐲',
      'spouting whale': '🐳',
      'horse face': '🐴',
      'monkey face': '🐵',
      'dog face': '🐶',
      'pig face': '🐷',
      'frog face': '🐸',
      'hamster face': '🐹',
      'wolf face': '🐺',
      'fox face': '🦊',
      'bear face': '🐻',
      'panda face': '🐼',
      'pig nose': '🐽',
      'paw prints': '🐾',
      //'grinning cat face with smiling eyes': '😸',
      //'cat face with tears of joy': '😹',
      //'smiling cat face with open mouth': '😺',
      //'smiling cat face with heart-shaped eyes': '😻',
      //'cat face with wry smile': '😼',
      //'kissing cat face with closed eyes': '😽',
      //'pouting cat face': '😾',
      //'crying cat face': '😿',
      //'weary cat face': '🙀',
      'see-no-evil monkey': '🙈',
      'speak-no-evil monkey': '🙊',
      'hear-no-evil monkey': '🙉',

    }

    let title_short = document.querySelector('#title_short')
    let title_long = document.querySelector('#title_long')

    let keys = Object.keys(symbols)
    let symbol = symbols[keys[Math.floor(keys.length * Math.random())]];
    title_short.innerHTML = symbol + ' AAPDX ' + symbol
    title_long.innerHTML = symbol + ' Animal Activism PDX ' + symbol


    // test code
    // let i = 0
    // setInterval(function() {
    //     let keys = Object.keys(symbols)
    //     let symbol = symbols[keys[i%keys.length]]
    //     i += 1
    //     title_short.innerHTML = symbol + ' PAA ' + symbol
    //     title_long.innerHTML = symbol + 'Portland Animal Activism' + symbol
    // }, 1000)

    let dont_expands = document.querySelectorAll('.dont_expand')
    for (let i=0; i<dont_expands.length; ++i) {
      // dont_expands[i].onclick = function(e) {
      //   e.stopPropagation();
      // }
      dont_expands[i].addEventListener('click', event => {
        event.stopPropagation();
      })
    }


  </script>
</body>

</html>

main/templates/main/about.html
{% extends 'main/base.html' %}
{% block title %} - About{% endblock %}
{% block main %}
<div class="page_title">About</div>
<p>We're rebranding from v-edge.io to ActiveWiki.org because the name is more descriptive and the .org tld is more widely recognized. ActiveWiki.org is also more flexible- it works as an organization name "ActiveWiki", a website "ActiveWiki.org", a short link "awiki.io", and a .wiki tld "active.wiki". Putting a lowercase proper noun in text is awkward, "V-edge" or "V-EDGE" are both also awkward, and nobody knows how to pronounce it. I still think v-edge is a cool name, but I'd rather build something that's actually used, and this will help.</p>
<p>Made with <3 by <a href="mailto:flux@activewiki.org">flux</a></p>


<h2>Guiding Principles</h2>
<table>
  <tr>
    <th>Positive (rights, justice, morality)</th>
    <th>Negative (oppression, ignorance, discrimination)</th>
  </tr>
  <tr>
    <td>Sentientism, Animal Rights, Veganism</td>
    <td>Speciesism, Carnism</td>
  </tr>
  <tr>
    <td>Humanism, Social Justice, Feminism, LGBTQ+</td>
    <td>Racism, Sexism, Sexualism, Classism, Ableism</td>
  </tr>
  <tr>
    <td>Environmentalism, Conservation</td>
    <td>Consumerism</td>
  </tr>
  <tr>
    <td>Democracy, Socialism</td>
    <td>Capitalism, Nationalism</td>
  </tr>
</table>

<h2>Statistics</h2>
<ul>
	<li>5325 lines of code</li>
	<li>638 events</li>
	<li>63 facts, 55 sources</li>
  <li>46 resources</li>
	<li>37 organizations</li>
	<li>8 communities</li>
	<li>6 sanctuaries</li>
</ul>

{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr" data-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0"> -->

    <title>ActiveWiki.org{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'main/images/favicon.ico' %}" />
    <meta name="description" content="ActiveWiki.org is a collection of tools and resources for enabling activism"/>
    <meta property="og:image" content="{% static 'main/images/banner.jpg' %}"/>
    <meta property="og:site_name" content="ActiveWiki.org"/>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-150088251-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-150088251-1');
    </script>



    <!-- normalize css -->
    <!-- <link href="https://unpkg.com/normalize.css@8.0.1/normalize.css" rel="stylesheet"/> -->
    <!-- vue.js -->
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <!-- materialize.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <!-- open sans -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet"/>

    <link href="{% static 'main/base.css' %}" rel="stylesheet"/>
    <script src="{% static 'main/helpers.js' %}"></script>

  </head>
  <body>
    <main>
      <ul id="dropdown_groups" class="dropdown-content">
        <li><a href="/organizations/">organizations</a></li>
        <li><a href="/communities/">communities</a></li>
        <li><a href="/sanctuaries/">sanctuaries</a></li>
      </ul>
      <nav>
        <div class="nav-wrapper">
          <a href="#" data-target="slide-out" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
          <a href="/" class="brand-logo">
            <a id="theme_switch"><img src="{% static 'main/images/logo_transparent_small.png' %}" class="logo"/></a>
            <a class="nav_title" href="/">ActiveWiki.org</a>
          </a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/events/">events</a></li>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown_groups">groups</a></li>
            <li><a href="/facts/">facts</a></li>
            <li><a href="/resources/">resources</a></li>
            <li><a href="{% url 'arvo:index' %}">outreach</a></li>
          </ul>

        </div>
      </nav>
      {% for message in messages %}
      <div class="message {{ message.tags }}">
        {{ message }}
      </div>
      {% endfor %}
      <div class="block_main">
        {% block main %}
        {% endblock %}
      </div>
    </main>
    <ul id="slide-out" class="sidenav">
      <li><a href="/events/">events</a></li>
      <li><a href="/organizations/">organizations</a></li>
      <li><a href="/communities/">communities</a></li>
      <li><a href="/sanctuaries/">sanctuaries</a></li>
      <li><a href="/facts/">facts</a></li>
      <li><a href="/resources/">resources</a></li>
      <li><a href="{% url 'arvo:index' %}">outreach</a></li>
    </ul>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems_sidenav = document.querySelectorAll('.sidenav');
        var instances_sidenav = M.Sidenav.init(elems_sidenav, {});

        let elems_dropdowns = document.querySelectorAll('nav .dropdown-trigger');
        let instances_dropdowns = M.Dropdown.init(elems_dropdowns, {
          alignment: 'right',
          coverTrigger: false,
          constrainWidth: false
        });
      });

      let theme_switch = document.querySelector('#theme_switch')
      theme_switch.onclick = function() {
        let root = document.documentElement

        let themes = ['dark', 'light']
        for (let i=0; i<themes.length; ++i) {
          let next_theme_id = (i+1)%themes.length;
          if (root.getAttribute('data-theme') == themes[i]) {
            root.setAttribute('data-theme', themes[next_theme_id])
            localStorage.setItem('theme', themes[next_theme_id])
            break
          }
        }
      }
      // localStorage.removeItem('theme')
      let theme = localStorage.hasOwnProperty('theme')? localStorage.getItem('theme'): 'dark'
      document.documentElement.setAttribute('data-theme', theme)


    </script>
  </body>
</html>

main/templates/main/cause.html
{% extends 'main/base.html' %}

{% block title %} - {{cause_name|title}}{% endblock %}

{% block main %}
<div class="page_title">{{cause_name|title}}</div>
{% endblock %}

main/templates/main/data_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} - {% if selected_tags %}{% for tag in selected_tags %}{{ tag.display_name}}{% if not forloop.last %} & {% endif %}{%endfor%} {% endif %}{{data_type | title}}{% if subdomain and data_type != 'facts' and data_type != 'resources' %} near {{ subdomain.name }}{% endif %}{% endblock %}
{% block main %}


{% include 'main/header.html' %}

<style type="text/css">
  .collapsible-header {
    display:flex;
    flex-direction:row;
    justify-content:space-between;
    align-items:stretch;
  }
  .collapsible > li {
    margin-bottom:40px;
  }
  .object_text {
    font-size:18px;
  }
  .title {
    font-size:26px;
  }
  .object_buttons {
    display:flex;
    flex-direction:column;
    justify-content:space-between;
    align-items:flex-end;
  }
  .object_buttons i {
      margin:5px;
  }

  .main_object_icon {
    margin:4px !important;
  }
  .collapsible > li.active i.expand_icon {
    -ms-transform: rotate(180deg); /* IE 9 */
    -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
    transform: rotate(180deg);
  }
  .links_share_bar {
    margin:20px 0;
  }
  .collapsible-body {
    padding:0;
  }

  .object_text ul {
    padding-left:20px;
  }


  .btn_share img {
    width:20px;
    margin:6px;
    transform:translateY(4px);
  }


  .group_link_buttons {
    text-align:right;
  }
  .group_description {
    margin:10px 0;
  }
</style>
<ul class="collapsible expandable">
  {% for object in objects %}
  <li>
    {% if data_type == 'events' %}
      {% include 'events/item.html' with event=object index=forloop.counter %}
    {% elif data_type == 'organizations' or data_type == 'communities' or data_type == 'sanctuaries' %}
      {% include 'groups/item.html' with group=object index=forloop.counter %}
    {% elif data_type == 'resources' %}
      {% include 'resources/item.html' with resource=object index=forloop.counter %}
    {% elif data_type == 'facts' %}
      {% include 'facts/item.html' with fact=object index=forloop.counter %}
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% include 'main/pagination.html' with objects=objects %}

<script type="text/javascript">

  let collapsible_instances = null

  document.addEventListener('DOMContentLoaded', function() {
    var collapsible_elems = document.querySelectorAll('.collapsible.expandable');
    collapsible_instances = M.Collapsible.init(collapsible_elems, {
      accordion: false
    });


    var elems_dropdowns = document.querySelectorAll('.collapsible .dropdown-trigger')
    // for (let i=0; i<elems_dropdowns.length; ++i) {
    //   elems_dropdowns[i].style.color = 'dimgrey'
    // }
    var instances_dropdowns = M.Dropdown.init(elems_dropdowns, {
      alignment: 'right',
      coverTrigger: false
    });

    let dont_expands = document.querySelectorAll('.dont_expand')
    for (let i=0; i<dont_expands.length; ++i) {
      dont_expands[i].addEventListener('click', event => {
        event.stopPropagation();
      })
    }
  });

</script>
{% endblock %}

main/templates/main/emoticons.html
{% extends 'main/base.html' %}
{% block title %} - Emoticons{% endblock %}
{% block main %}
<h1>Emoticons</h1>
{% endblock %}

main/templates/main/get_active.html
{% extends 'main/base.html' %}
{% block title %} - Get Active{% endblock %}
{% block main %}
<style type="text/css">

  .collapsible-header {
    margin-bottom:20px;
    text-align:center;
    display:block;
    font-size:24px;
    color: var(--collapsible-header-link-color);
  }
  p {
    text-align:center;
    max-width:500px;
    margin: 0 auto;
    margin-bottom: 20px;
  }
</style>
<div class="page_title_center">Get Active PDX</div>
<ul class="children collapsible expandable">
  <li>
    <a class="collapsible-header" href="https://www.facebook.com/groups/pdxaa/">Portland Animal Activism</a>
    <a class="collapsible-header" href="/events/animals/">Events</a>
    <a class="collapsible-header" href="/organizations/animals/">Organizations</a>
    <a class="collapsible-header" href="/resources/animals/">Resources</a>
  </li>
</ul>
<p>Every day, millions of animals are unnecessarily exploited and slaughtered for food, clothing, experimentation, and entertainment. Their suffering is ignored and hidden by deceptive advertising. These animals need your voice. You can make a difference.</p>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}{% endblock %}
{% block main %}
<style type="text/css">

  .collapsible-header {
    margin-bottom:10px;
    text-align:center;
    display:block;
    font-size:24px;
  }
  .home_header {
    font-size:24px;
    text-align:center;
    margin:20px;
  }
  .home_footer {
    font-size:16px;
    text-align:center;
    padding-bottom:20px;
  }
</style>
<div class="home_header">ActiveWiki.org is a collection of resources for enabling activism</div>

<ul class="collapsible expandable">
  {% for link in links %}
  <li>
    <a class="collapsible-header" href="/{{link}}/">{{link}}</a>
  </li>
  {% endfor %}
</ul>
<div class="home_footer">Comments, suggestions, problems? Message <a href="mailto:flux@activewiki.org">flux@activewiki.org</a></div>
{% endblock %}